# Generated by Django 6.0.3 on 2026-06-16 13:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_cours', models.CharField(editable=False, max_length=20, unique=True)),
                ('nom_cours', models.CharField(max_length=200)),
                ('ponderation', models.DecimalField(decimal_places=2, max_digits=4)),
                ('points', models.IntegerField()),
                ('credit', models.DecimalField(decimal_places=1, default=3.0, max_digits=3)),
                ('volume_horaire', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('ordre', models.IntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(editable=False, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_embauche', models.DateField()),
                ('specialite', models.CharField(blank=True, max_length=200, null=True)),
                ('tentative_connexion', models.IntegerField(default=0)),
                ('bloque_jusqua', models.DateTimeField(blank=True, null=True)),
                ('date_derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professeurs', to='etudiants.faculte')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professeurs', to='enseignements.grade')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='GestionApplicationCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('annee_academique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etudiants.anneeacademique')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='enseignements.cours')),
                ('faculte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etudiants.faculte')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etudiants.promotion')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications_cours', to='enseignements.professeur')),
            ],
            options={
                'verbose_name': 'Gestion application de cours',
                'verbose_name_plural': 'Gestion applications de cours',
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours_responsables', to='enseignements.professeur'),
        ),
        migrations.CreateModel(
            name='SessionConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('date_connexion', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_expiration', models.DateTimeField()),
                ('est_active', models.BooleanField(default=True)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='enseignements.professeur')),
            ],
            options={
                'ordering': ['-date_connexion'],
            },
        ),
        migrations.CreateModel(
            name='AppliquerCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_application', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_appliques', to='etudiants.etudiant')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants_assignes', to='enseignements.cours')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_individuelles', to='enseignements.gestionapplicationcours')),
            ],
            options={
                'verbose_name': 'Cours appliqué',
                'verbose_name_plural': 'Cours appliqués',
                'unique_together': {('gestion', 'etudiant', 'cours')},
            },
        ),
        migrations.AddIndex(
            model_name='professeur',
            index=models.Index(fields=['matricule'], name='enseignemen_matricu_00711d_idx'),
        ),
        migrations.AddIndex(
            model_name='professeur',
            index=models.Index(fields=['email'], name='enseignemen_email_e68fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='professeur',
            index=models.Index(fields=['est_actif'], name='enseignemen_est_act_237fde_idx'),
        ),
        migrations.AddIndex(
            model_name='professeur',
            index=models.Index(fields=['faculte'], name='enseignemen_faculte_5d404c_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionconnexion',
            index=models.Index(fields=['token'], name='enseignemen_token_faf33e_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionconnexion',
            index=models.Index(fields=['est_active'], name='enseignemen_est_act_132a84_idx'),
        ),
    ]
