# Generated by Django 6.0.3 on 2026-06-21 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sessionconnexion',
            name='enseignemen_token_faf33e_idx',
        ),
        migrations.RemoveIndex(
            model_name='sessionconnexion',
            name='enseignemen_est_act_132a84_idx',
        ),
        migrations.AddField(
            model_name='professeur',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professeur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SessionConnexion',
        ),
    ]
