# Generated by Django 6.0.3 on 2026-07-04 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enseignements', '0008_decision_jury'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotationsession',
            options={'ordering': ['-session__date_debut', 'application__cours__nom_cours'], 'verbose_name': 'Cotation par session', 'verbose_name_plural': 'Cotations par session'},
        ),
        migrations.AlterModelOptions(
            name='decisionjury',
            options={'ordering': ['etudiant__nom', 'etudiant__prenom'], 'verbose_name': 'Décision du jury', 'verbose_name_plural': 'Décisions du jury'},
        ),
        migrations.AlterModelOptions(
            name='sessionevaluation',
            options={'ordering': ['-date_debut', 'nom'], 'verbose_name': "Session d'évaluation", 'verbose_name_plural': "Sessions d'évaluation"},
        ),
    ]
