# Generated by Django 6.0.3 on 2026-07-07 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignements', '0009_alter_cotationsession_options_and_more'),
        ('etudiants', '0007_inscriptionacademique'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionevaluation',
            name='est_cloture',
            field=models.BooleanField(default=False, verbose_name='Session de clôture du jury'),
        ),
        migrations.AddField(
            model_name='sessionevaluation',
            name='sessions_incluses',
            field=models.ManyToManyField(blank=True, related_name='clotures_associees', to='enseignements.sessionevaluation', verbose_name='Sessions à consolider'),
        ),
        migrations.AlterField(
            model_name='decisionjury',
            name='decision',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ADMIS', 'Admis'), ('AJOURNE', 'Ajourné'), ('NON_ADMIS', 'Non admis')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='PromotionEnAttente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PROMU', 'Promu'), ('BLOQUE', 'Bloqué')], default='EN_ATTENTE', max_length=12)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('annee_cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions_recues', to='etudiants.anneeacademique')),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_attendue', to='enseignements.decisionjury')),
                ('inscription_creee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_source', to='etudiants.inscriptionacademique')),
                ('inscription_origine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions_emises', to='etudiants.inscriptionacademique')),
                ('promotion_cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions_recues', to='etudiants.promotion')),
            ],
            options={
                'verbose_name': 'Promotion en attente',
                'verbose_name_plural': 'Promotions en attente',
                'ordering': ['-date_creation'],
            },
        ),
    ]
