# Generated by Django 6.0.3 on 2026-07-07 12:23

import django.db.models.deletion
from django.db import migrations, models


def supprimer_attentes_en_double(apps, schema_editor):
    PromotionEnAttente = apps.get_model('enseignements', 'PromotionEnAttente')
    inscriptions = PromotionEnAttente.objects.values_list('inscription_origine_id', flat=True).distinct()
    for inscription_id in inscriptions:
        ids = list(PromotionEnAttente.objects.filter(
            inscription_origine_id=inscription_id,
        ).order_by('-id').values_list('id', flat=True))
        if len(ids) > 1:
            PromotionEnAttente.objects.filter(id__in=ids[1:]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('enseignements', '0010_sessionevaluation_est_cloture_and_more'),
        ('etudiants', '0007_inscriptionacademique'),
    ]

    operations = [
        migrations.RunPython(supprimer_attentes_en_double, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='promotionenattente',
            name='inscription_origine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_emise', to='etudiants.inscriptionacademique'),
        ),
    ]
