# Generated by Django 6.0.3 on 2026-06-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='mot_de_passe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mot de passe'),
        ),
    ]
