# Generated by Django 6.0.3 on 2026-07-04 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0004_departement_etudiant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departement',
            options={'ordering': ['faculte__nom', 'nom'], 'verbose_name': 'Département', 'verbose_name_plural': 'Départements'},
        ),
    ]
