# Generated by Django 6.0.3 on 2026-07-07 09:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


def creer_historique_existant(apps, schema_editor):
    Etudiant = apps.get_model('etudiants', 'Etudiant')
    Inscription = apps.get_model('etudiants', 'InscriptionAcademique')
    for etudiant in Etudiant.objects.exclude(annee_academique_id=None).select_related('annee_academique'):
        annee = etudiant.annee_academique
        date_inscription = etudiant.date_inscription
        if date_inscription < annee.date_debut:
            date_inscription = annee.date_debut
        elif date_inscription > annee.date_fin:
            date_inscription = annee.date_fin
        Inscription.objects.get_or_create(
            etudiant_id=etudiant.id,
            annee_academique_id=annee.id,
            defaults={
                'faculte_id': etudiant.faculte_id,
                'departement_id': etudiant.departement_id,
                'promotion_id': etudiant.promotion_id,
                'date_inscription': date_inscription,
                'est_courante': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0006_etudiant_matricule_automatique'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('INSCRIT', 'Inscrit'), ('ADMIS', 'Admis au niveau suivant'), ('AJOURNE', 'Ajourné'), ('TERMINE', 'Cursus terminé')], default='INSCRIT', max_length=12)),
                ('date_inscription', models.DateField(default=datetime.date.today)),
                ('est_courante', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions_etudiants', to='etudiants.anneeacademique')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etudiants.departement')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_academiques', to='etudiants.etudiant')),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etudiants.faculte')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etudiants.promotion')),
            ],
            options={
                'verbose_name': 'Inscription académique',
                'verbose_name_plural': 'Inscriptions académiques',
                'ordering': ['-annee_academique__date_debut'],
                'constraints': [models.UniqueConstraint(fields=('etudiant', 'annee_academique'), name='unique_inscription_etudiant_annee')],
            },
        ),
        migrations.RunPython(creer_historique_existant, migrations.RunPython.noop),
    ]
