# Generated by Django 6.0.3 on 2026-06-06 22:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Type de frais')),
                ('code', models.SlugField(blank=True, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Type de frais',
                'verbose_name_plural': 'Types de frais',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='FraisAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_specialisation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Option / Spécialisation')),
                ('semestre', models.IntegerField(choices=[(1, '1er Semestre'), (2, '2ème Semestre')], verbose_name='Semestre')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total à payer')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_academiques', to='etudiants.anneeacademique', verbose_name='Année académique')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_academiques', to='etudiants.etudiant', verbose_name='Étudiant')),
                ('faculte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frais_academiques', to='etudiants.faculte', verbose_name='Faculté')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frais_academiques', to='etudiants.promotion', verbose_name='Promotion')),
                ('type_frais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frais_academiques', to='frais_academique.typefrais', verbose_name='Type de frais')),
            ],
            options={
                'verbose_name': 'Frais académique',
                'verbose_name_plural': 'Frais académiques',
                'unique_together': {('etudiant', 'annee_academique', 'semestre', 'type_frais')},
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé')),
                ('date_paiement', models.DateField(default=django.utils.timezone.now, verbose_name='Date de paiement')),
                ('mode_paiement', models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('banque', 'Virement bancaire'), ('cheque', 'Chèque'), ('carte', 'Carte bancaire')], max_length=50, verbose_name='Mode de paiement')),
                ('reference', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Numéro de reçu')),
                ('statut', models.CharField(choices=[('valide', 'Validé'), ('annule', 'Annulé'), ('en_attente', 'En attente')], default='valide', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='etudiants.etudiant', verbose_name='Étudiant')),
                ('frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='frais_academique.fraisacademique', verbose_name='Frais concernés')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='TarifFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_specialisation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Option / Spécialisation')),
                ('semestre', models.IntegerField(choices=[(1, '1er Semestre'), (2, '2ème Semestre')], verbose_name='Semestre')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_frais', to='etudiants.anneeacademique', verbose_name='Année académique')),
                ('faculte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_frais', to='etudiants.faculte', verbose_name='Faculté')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_frais', to='etudiants.promotion', verbose_name='Promotion')),
                ('type_frais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs', to='frais_academique.typefrais', verbose_name='Type de frais')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifs',
                'unique_together': {('faculte', 'promotion', 'option_specialisation', 'semestre', 'type_frais', 'annee_academique')},
            },
        ),
    ]
